version: '3.8'
services:
  inventory-db:
    container_name: inventory-db
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: inventory-db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - inventory-pg:/var/lib/postgresql/data
    restart: unless-stopped
  
volumes:
  inventory-pg:
